### ISSUE TITLE
MOOC's Brayns Launcher - Status: Failed

### ISSUE THREAD

**Issue by laviniamitiko** [BlueBrain/MOOC-hippocampus-network-simulation-2019#39]
Hey there,

I'm taking the course Simulating a hippocampus microcircuit, the content of week 2, but I was unable to open the viewer. I tried it more than once and every time Status: Failed appeared, how can I fix this to continue with the course? I attached the file containing the troubleshooting. 

[Brayns (1).log](https://github.com/BlueBrain/MOOC-hippocampus-network-simulation-2019/files/6126750/Brayns.1.log)

**Comment by antonelepfl** [comment]
We have contacted the person in charge of that week to have a look. We will come back to you soon.

**Comment by ppodhajski** [comment]
Hello @laviniamitiko,
thanks for your bug report. It seems a job scheduling mechanism has been changed. I just deployed a patched version, would you mind trying it now and letting me know the result?

**Comment by laviniamitiko** [comment]
Hello guys, 
Now it's working perfectly!

Thank you so much for fixing it!
