### ISSUE TITLE
Issue while submitting the assignment

### ISSUE THREAD

**Issue by vignan21** [BlueBrain/MOOC-hippocampus-network-simulation-2019#40]
Hi,

While submitting my assignment, the following error below popped.

Week 3: Assignment bouton density

The grading process failed to complete. Please double-check your answer or contact the organizers of the course with the following information: [params: {'submission_token': 'uTAZTltxlIM0cdMzzp67hqXZtFOe', 'answer': '{"ans_1a": 0.13861392961943844, "ans_1b": 0.13326876666581175, "ans_2a": 0.1287691645391, "ans_2b": 0.12300483362079291}'} , exception: zip argument #1 must support iteration].

Thank you

**Comment by antonelepfl** [comment]
Do you have any update on this?

**Comment by stefanoantonel** [comment]
If this is not an issue anymore, I'll close this.
Please re-open or create a new one if the issue persist.
