### ISSUE TITLE
Extension of the term of activities

### ISSUE THREAD

**Issue by laviniamitiko** [BlueBrain/MOOC-hippocampus-network-simulation-2019#46]
Hello how are you?

Me and some other students are finding problems to finalize some assignments, I posted on the discussion forum, but we didn't find any solution. So I'm stuck on the activities of week 3, today I'm going to finish the quizzes, but I was wondering if they could increase the deadline by one or two days, or help us to finish this week's topic.

**Comment by antonelepfl** [comment]
Hello,
The course was extended
