### ISSUE TITLE
Error when submitting my responses to graded quiz 2

### ISSUE THREAD

**Issue by laviniamitiko** [BlueBrain/MOOC-hippocampus-network-simulation-2019#47]
When I select the answer to submit in graded quiz 2, the submit button does not work.

![GradedIssue](https://user-images.githubusercontent.com/72054479/116320550-ceb38c00-a78e-11eb-8f94-e6ac66eda28c.png)

The button is gray like this, so I can't submit my answers to this quizz.

**Comment by Annechien** [comment]
I had the problem too. But could you check again. Because the problem no longer exists for me.

**Comment by jdcourcol** [comment]
that is quite some time with no news. I consider we can close this.
