### ISSUE TITLE
[SYNPASE VALIDATION] The platform for validation is missing

### ISSUE THREAD

**Issue by laviniamitiko** [BlueBrain/MOOC-hippocampus-network-simulation-2019#49]
Hello everyone, everything good?
In the activities of week 4, more specifically, the assignment synapse validation does not contain the platform used in the video for validation. Below I put the image of the platform that I was waiting to be able to carry out the validations. Can you guys update this lesson? I'll be posting it at the forum too, because I didn't know if in this case it was an error in the structuring or related to the platforms used.

![image](https://user-images.githubusercontent.com/72054479/117592472-074c5180-b10f-11eb-820e-34a8839b8e52.png)

**Comment by antonelepfl** [comment]
Hi !
Thank you for reporting this. I have updated the link in the exercise 
Anyhow, the link should be https://psp-validation.apps.hbp.eu/
